### ISSUE TITLE
No custom button on lord recruitment screen

### ISSUE THREAD

**Issue by Uzhirian** [Vanishoxyact/custom-lords#1]
Started a new campaign. Disabled all mods but custom_lord and prereqs. Unsubscribed and resubbed.

Logs attached
[script_log_110520_2013.txt](https://github.com/Vanishoxyact/custom-lords/files/4608974/script_log_110520_2013.txt)
[script_log_110520_2014.txt](https://github.com/Vanishoxyact/custom-lords/files/4608975/script_log_110520_2014.txt)
[used_mods.txt](https://github.com/Vanishoxyact/custom-lords/files/4608976/used_mods.txt)

**Comment by Vanishoxyact** [comment]
Hopefully fixed now.
