### ISSUE TITLE
Issue with lizardmen heroes on Nakai (horde)

### ISSUE THREAD

**Issue by antdood** [Vanishoxyact/custom-lords#4]
Nakai campaign.

I am way below the cap for skin priests but am unable to recruit a custom one. Saurus scar veterans are also in the same state. 

![image](https://user-images.githubusercontent.com/11871073/82119028-b335b800-97ad-11ea-8dfd-f6d7e47d9461.png)

However, Skink Chiefs are working fine as you can see 
![here](https://user-images.githubusercontent.com/11871073/82119058-f2fc9f80-97ad-11ea-93fa-d4b2c69b191b.png). 

At some point earlier in the campaign, the custom recruitment for Saurus Scar Veterans was functioning fine. I believe it has to do with Nakai's campaign blessing "Skink Priests of Distinction" and it's counterparts. However, I still can't pinpoint the issue. Even after using "Skink Chiefs of Distinction", custom Skink Chiefs are still recruitable.

**Comment by Vanishoxyact** [comment]
Thanks for the info. I've just pushed a new version to the workshop, hopefully it fixes it.

**Comment by antdood** [comment]
I'll give it a go. Thanks! Also, let me know if you want some help on this. I'm a software dev with time to spare :)

**Comment by antdood** [comment]
Fixed, working fine now. What was the issue anyways?

**Comment by Vanishoxyact** [comment]
Thanks for the offer! I think most of the coding is done now though, it's mostly data changes (like adding new traits, skill sets) unless you'd also like to look into that. The main issue was i was doing a string compare rather than number compare, so "2" was coming out greater than "10".
